### ISSUE TITLE
file manager

### ISSUE THREAD

**Issue by ocanty** [UCCNetsoc/cloud#13]
should implement all the standard stuff they can do at the command line

**Comment by ericm** [comment]
- ui

**Comment by ocanty** [comment]
`/files/<username>/`




Implementor should look here: https://github.com/UCCNetsoc/admin/blob/master/api/v1/providers/backups.py#L91

List a directory `GET /files/<username>/ls/<some path>`
Touch a directory `POST /files/<username>/directory/<some path>` `default -p`
Delete a directory (default recursive) `DELETE /files/<username>/directory/<some path>`

Download a directory (tar.gz)  `GET /files/<username>/directory/<some path>`

Upload a file `POST /files/<username>/file/<some path>`
Stat a file `GET /files/<username>/stat/<some path>` _should work for everything including directories, links, etc..._
Download a file `GET /files/<username>/file/<some path>` targz unless it's below a certain size
Delete a file `DELETE /files/<username>/file/<some path>

Chmod `PUT /files/<username>/chown/<some path>` have a option for recursive

**Comment by ocanty** [comment]
redundant, replaced by monstaftp
